# Site settings
title: Vektrix Engineering
email: engineering@vektrix.in
description: > # this means to ignore newlines until "baseurl:"
 Vektrix provides engineering analytics solutions for the modern web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vektrix.in" # the base hostname & protocol for your site
twitter_username: arakhneio
github_username:  vektrix

# Build settings
markdown: kramdown
